const keys = require('../../config/keys')
import LocalizedStrings from 'react-localization';

import MediaPreview from './media-preview'
const mediaQuery = '/get-media-templates'
const pexelsQuery = '/get-pexels-templates'

let strings = new LocalizedStrings({
    en:{
        designLabel: "Design / Media",
        badgeLabel: "Badges",
        photosLabel: "Photos (Pexels)",
        illustrationsLabel: "Illustrations",
        shapesLabel: "Shapes",
        iconsLabel: "Icons"
    },
    kr: {
        designLabel: "디자인 / 미디어",
        badgeLabel: "뱃지",
        photosLabel: "사진 (Pexels)",
        illustrationsLabel: "일러스트",
        shapesLabel: "모양",
        iconsLabel: "아이콘"
    }
});
strings.setLanguage(process.env.LANGUAGE ? process.env.LANGUAGE : 'en')


const iconTags = [
    "arrow",
    "cancel",
    "download",
    "icons",
    "bold",
    "edit",
    "tools",
    "close",
    "signs",
    "storage",
    "business",
    "inbox",
    "online",
    "education",
    "technology",
    "media",
    "zoom",
    "shopping",
    "social",
    "back",
    "rotate",
    "image",
    "file",
    "nature",
    "animal",
    "cloud",
    "ui",
    "click",
    "move",
    "drag",
    "video",
    "cursor",
    "photo"
]

const shapeTags = [
    "blob",
    "arrows",
    "chart",
    "basic",
    "wave",
    "iceburg",
    "animal",
    "card",
    "weather",
    "message"
]

const badgeTags = [
    "spring ",
    "summer ",
    "fall",
    "winter ",
    "new years",
    "valentines ",
    "mother's day",
    "father's day ",
    "parent's day",
    "halloween",
    "thanksgiving day",
    "black friday",
    "cyber monday",
    "christmas",
    "technology",
    "software",
    "business",
    "education",
    "fashion",
    "food",
    "logistics",
    "charts",
    "diagrams",
    "web design",
    "event",
    "gym",
    "america",
    "avatar",
    "emoji",
    "love",
    "email",
    "culture",
    "beauty",
    "party",
    "geography",
    "map",
    "country",
    "korea",
    "birthday",
    "phone",
    "tour",
    "game",
    "sports",
    "awards",
    "manufacturing",
    "sale",
    "animal",
    "camping",
    "science",
    "logo",
    "paypal",
    "visa",
    "mastercard",
    "guarantee",
    "free",
    "shopping"
]
const illustrationTags = [
    "chart",
    "share",
    "logo",
    "card",
    "settings",
    "text",
    "gift",
    "online",
    "creative",
    "business",
    "website",
    "photo",
    "profile",
    "mobile",
    "inbox",
    "nature",
    "information",
    "app",
    "design",
    "data",
    "button",
    "ux",
    "stock",
    "love",
    "party",
    "camping",
    "shopping",
    "job",
    "learning",
    "video",
    "chat",
    "progress",
    "home",
    "product",
    "audio",
    "crypto",
    "cooking",
    "reading",
    "web",
    "medical",
    "conference",
    "social",
    "world",
    "build",
    "download",
    "fitness",
    "investment",
    "art",
    "welcome",
    "feeling",
    "calendar",
    "certification",
    "location",
    "cloud",
    "analysis",
    "car",
    "team",
    "account",
    "work",
    "factory",
    "friends",
    "date",
    "travel",
    "article",
    "xmas",
    "tutorial",
    "authentication",
    "environmental",
    "project",
    "pay",
    "delivery",
    "code",
    "spooky",
    "unicorn",
    "abstract",
    "healthy",
    "connection",
    "image",
    "people",
    "thought",
    "story",
    "smart",
    "weather",
    "animating",
    "futuristic",
    "female",
    "male",
    "heatmap",
    "referral",
    "dream",
    "trendy",
    "pet",
    "fresh",
    "ideas",
    "activity",
    "group",
    "hangout",
    "chats",
    "newspaper",
    "winter",
    "summer",
    "spring",
    "fall",
    "developer",
    "clean",
    "art",
    "goals",
    "everyday",
    "fun",
    "click",
    "money",
    "influencer",
    "flowers",
    "happy",
    "mathematics",
    "album",
    "road",
    "speech",
    "server",
    "city",
    "personal",
    "fashion",
    "multitasking",
    "coffee",
    "page",
    "software",
    "financial",
    "dog",
    "ninja",
    "growth",
    "career",
    "followers",
    "hiking",
    "timeline",
    "discount",
    "festivities",
    "mind",
    "christmas",
    "game",
    "construction",
    "gifts",
    "logistics",
    "vehicle",
    "prototyping",
    "robotics",
    "revenue",
    "wallet",
    "warning",
    "winners",
    "features",
    "interview",
    "questions",
    "children",
    "security",
    "thank",
    "site",
    "dashboard",
    "envelope",
    "preferences",
    "trip",
    "science",
    "conversation",
    "studying",
    "school",
    "list",
    "music",
    "startup",
    "doctor",
    "birthday",
    "park",
    "loading",
    "successful",
    "beach",
    "community",
    "gdpr",
    "podcast",
    "friendship",
    "artifitial intelligence",
    "bitcoin",
    "checklist",
    "movie",
    "setup",
    "mail",
    "woman",
    "blog",
    "map",
    "credit card"
]


const mediaTags = [
    'minimalistic', 
    'colorful', 
    'basic',
    'edgy',
    'round'
]

const media = {
    tags: [
        ...mediaTags
    ],
    name: strings.designLabel,
    options: [
        {
            tags: badgeTags,
            query: mediaQuery,
            category: keys.BADGE_CATEGORY,
            templateType: keys.MEDIA_TEMPLATE,
            text: strings.badgeLabel,
            render: MediaPreview,
            width: 10,
            padding: 25
        },
        {
            tags: badgeTags,
            query: pexelsQuery,
            category: keys.PHOTOGRAPH_CATEGORY,
            templateType: keys.MEDIA_TEMPLATE,
            text: strings.photosLabel,
            render: MediaPreview,
            width: 25,
            padding: 10
        },
        {
            tags: illustrationTags,
            query: mediaQuery,
            category: keys.ILLUSTRATION_CATEGORY,
            templateType: keys.MEDIA_TEMPLATE,
            text: strings.illustrationsLabel,
            render: MediaPreview,
            width: 25,
            padding: 40
        },
        {
            tags: shapeTags,
            query: mediaQuery,
            category: keys.SHAPE_CATEGORY,
            templateType: keys.MEDIA_TEMPLATE,
            text: strings.shapesLabel,
            render: MediaPreview,
            width: 10,
            padding: 25
        },
        {
            tags: iconTags,
            query: mediaQuery,
            category: keys.ICON_CATEGORY,
            templateType: keys.MEDIA_TEMPLATE,
            text: strings.iconsLabel,
            render: MediaPreview,
            width: 10,
            padding: 25
        }
    ]
}


let templateOptionsExport = {}
templateOptionsExport[keys.MEDIA_TEMPLATE] = media

export default templateOptionsExport